### ISSUE TITLE
Bug: 处理好友请求时报错

### ISSUE THREAD

**Issue by Aliorpse** [KarinJS/Karin#182]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是最新版本的`Karin`
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

## 描述问题

加机器人好友然后报错

## 复现步骤

详细描述如何复现该问题：

加机器人好友

## 预期行为

通过好友

## 实际行为

报错

## 环境信息

- 操作系统：winserver 2022
- Node.js 版本：v20.15.1
- 项目版本：latest

## 附加信息

```
[Karin][18:15:19.939][INFO] [Bot:3982775852] [好友添加]：{"time":1727604919,"self_id":3982775852,"post_type":"notice","notice_type":"friend_add","user_id":这是用户id}
[Karin][18:15:19.941][ERRO] TypeError: Cannot read properties of undefined (reading 'scene')
    at NoticeHandler.init (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/event/handler/notice.js:40:28)
    at new NoticeHandler (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/event/handler/notice.js:13:14)
    at Karin.<anonymous> (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/core/listener/listener.js:29:43)
    at Karin.emit (node:events:519:28)
    at Karin.emit (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/core/listener/listener.js:37:22)
    at OB11Event.noticeEvent (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/adapter/onebot/11/event.js:388:18)
    at OB11Event.event (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/adapter/onebot/11/event.js:22:22)
    at AdapterOneBot11.init (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/adapter/onebot/11/index.js:94:33)
    at WebSocket.<anonymous> (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.14/node_modules/node-karin/lib/adapter/onebot/11/index.js:70:25)
    at WebSocket.emit (node:events:519:28)
```

**Comment by shijinn520** [comment]
用的啥适配器。

**Comment by Aliorpse** [comment]
> 用的啥适配器。

napcat2.6.15

**Comment by shijinn520** [comment]
> > 用的啥适配器。
> 
> napcat2.6.15

好的 等我病好看一下。

**Comment by Aliorpse** [comment]
> > > 用的啥适配器。
> > 
> > 
> > napcat2.6.15
> 
> 好的 等我病好看一下。

okok，感谢

**Comment by shijinn520** [comment]
```js
import karin from 'node-karin'

export const test = karin.accept('request.private_apply', async (e) => {
  await e.bot.SetFriendApplyResult(e.content.flag, true)
})
```

**Comment by Aliorpse** [comment]
额我bot号现在被封了（
没法测试

**Comment by Aliorpse** [comment]
昨晚看见忘回了qwq
