### ISSUE TITLE
Bug: 处理临时会话时出错

### ISSUE THREAD

**Issue by Aliorpse** [KarinJS/Karin#195]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是最新版本的`Karin`
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

## 描述问题

如题

## 复现步骤

临时会话发送消息

## 预期行为

预期应该发生什么？

## 实际行为

实际发生了什么？

## 环境信息

- 操作系统：winserver2022
- Node.js 版本 v20
- 项目版本：0.12.17

## 附加信息

```js
[Karin][22:30:39.604][INFO] [Bot:3948157806] 私聊：[3521766148(临时会话)] ok
[Karin][22:30:39.605][ERRO] TypeError: Cannot read properties of undefined (reading 'GroupUserCD')
    at Handler.CD (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.17/node_modules/node-karin/lib/event/handler/review.js:305:71)
    at MessageHandler.getCd (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.17/node_modules/node-karin/lib/event/handler/base.js:21:20)
    at MessageHandler.start (file:///C:/Users/Administrator/Desktop/karin/node_modules/.pnpm/node-karin@0.12.17/node_modules/node-karin/lib/event/handler/message.js:21:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by shijinn520** [comment]
哪个协议

**Comment by Aliorpse** [comment]
NapCatQQ

**Comment by lava081** [comment]
Lagrange.OneBot复现成功

**Comment by lava081** [comment]
raw_event: {
    message_type: 'private',
    sub_type: 'group',
    ...
  },
