### ISSUE TITLE
Bug: 通过`#更新`更新karin失败

### ISSUE THREAD

**Issue by Aliorpse** [KarinJS/Karin#198]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是最新版本的`Karin`
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

## 描述问题

如题

## 复现步骤

详细描述如何复现该问题：

1. 发送#更新

## 预期行为

karin更新到最新版本

## 实际行为

报错

## 环境信息

- 操作系统：winserver2022
- Node.js 版本：v20
- 项目版本：v..17

## 附加信息

```js
[Karin][22:48:41.283][INFO] [exec][开始执行]
cmd: pnpm install -P
cwd: C:\Users\Administrator\Desktop\karin

--------
[Karin][22:48:42.252][INFO] [exec][执行成功]
cmd: pnpm install -P
cwd: C:\Users\Administrator\Desktop\karin
stdout: Scope: all 3 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date

devDependencies: skipped

Done in 897ms

stderr:
--------
[Karin][22:48:42.253][INFO] [exec][开始执行]
cmd: npx node-karin init
cwd: C:\Users\Administrator\Desktop\karin

--------
[Karin][22:48:43.852][INFO] [exec][执行失败]
cmd: npx node-karin init
cwd: C:\Users\Administrator\Desktop\karin
Error: Command failed: npx node-karin init
npm error could not determine executable to run
npm error A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-11-22T14_48_42_473Z-debug-0.log
--------
```

相关npm缓存日志:
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.8.3
2 info using node@v20.15.1
3 silly config load:file:C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\npmrc
4 silly config load:file:C:\Users\Administrator\Desktop\karin\.npmrc
5 silly config load:file:C:\Users\Administrator\.npmrc
6 silly config load:file:C:\Users\Administrator\AppData\Roaming\npm\etc\npmrc
7 verbose title npm exec node-karin init
8 verbose argv "exec" "--" "node-karin" "init"
9 verbose logfile logs-max:10 dir:C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-11-22T14_48_42_473Z-
10 verbose logfile C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-11-22T14_48_42_473Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
14 verbose stack Error: could not determine executable to run
14 verbose stack     at getBinFromManifest (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
14 verbose stack     at exec (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:202:15)
14 verbose stack     at async Npm.exec (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\npm.js:207:9)
14 verbose stack     at async module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\cli\entry.js:74:5)
15 verbose pkgid node-karin@0.12.17
16 error could not determine executable to run
17 verbose cwd C:\Users\Administrator\Desktop\karin
18 verbose os Windows_NT 10.0.20348
19 verbose node v20.15.1
20 verbose npm  v10.8.3
21 verbose exit 1
22 verbose code 1
23 error A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-11-22T14_48_42_473Z-debug-0.log
```

**Comment by shijinn520** [comment]
更新到最新版。

**Comment by Aliorpse** [comment]
> 更新到最新版。

自己试了`npx node-karin init`,出现同样报错
还是有其他办法更新呢

**Comment by Aliorpse** [comment]
已解决
